version: '3.7'

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:15
    container_name: grafana-postgres
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grafana-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Serviço Grafana
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ertis-opentwins
      - GF_LOG_LEVEL=debug
      # Configurações do PostgreSQL
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      # Otimizações para PostgreSQL
      - GF_DATABASE_MAX_OPEN_CONN=25
      - GF_DATABASE_MAX_IDLE_CONN=25
      - GF_DATABASE_CONN_MAX_LIFETIME=14400
    volumes:
      - grafana_data:/var/lib/grafana
      - ./plugins/digital-twins-plugin-for-grafana/dist:/var/lib/grafana/plugins/ertis-opentwins
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grafana-net

# Redes e volumes
networks:
  grafana-net:
    driver: bridge

volumes:
  grafana_data:
  postgres_data:
